In [ ]:
## Completed Pages:----
    # 03.00-Introduction-to-Pandas.ipynb
    # 03.01-Introducing-Pandas-Objects.ipynb
    # 03.02-Data-Indexing-and-Selection.ipynb
    # 03.03-Operations-in-Pandas.ipynb
    # 03.04-Missing-Values.ipynb
    # 03.05-Hierarchical-Indexing.ipynb
    # 03.06-Concat-And-Append.ipynb
    # 03.07-Merge-and-Join.ipynb

In [154]:
import pandas
pandas.__version__
import pandas as pd
pd??

Type:        module
String form: <module 'pandas' from '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pandas/__init__.py'>
File:        /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pandas/__init__.py
Source:     
from __future__ import annotations

import os
import warnings

__docformat__ = "restructuredtext"

# Let users know if they're missing any of our hard dependencies
_hard_dependencies = ("numpy", "pytz", "dateutil")
_missing_dependencies = []

for _dependency in _hard_dependencies:
    try:
        __import__(_dependency)
    except ImportError as _e:  # pragma: no cover
        _missing_dependencies.append(f"{_dependency}: {_e}")

if _missing_dependencies:  # pragma: no cover
    raise ImportError(
        "Unable to import required dependencies:\n" + "\n".join(_missing_dependencies)
    )
del _hard_dependencies, _dependency, _missing_dependencies

try:
    # numpy compat
    from pandas.compat import (
     

In [155]:
import numpy as np
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

data.values
data[1]
data[1:3]
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])
data
data['b']

data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = [2, 5, 3, 7])
data
data[5]

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

population = pd.Series(population_dict)
population
population['California']
population['California':'Illinois']

pd.Series([2, 4, 6])
pd.Series({2:'a', 1:'b', 3:'c'})
pd.Series({2:'a', 1:'b', 3:'c'}, index = [3, 2])

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

states = pd.DataFrame({'population': population,
                       'area': area})
states
states.index
states.columns
states['area']
pd.DataFrame(population, columns = ['population'])

data = [{'a': i, 'b': 2 * i} 
        for i in range(21)]
pd.DataFrame(data)

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

pd.DataFrame({'population': population, 'area': area})

pd.DataFrame(np.random.rand(3, 2),
             columns = ['foo', 'bar'],
             index = ['a', 'b', 'c'])

A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')]);
print(A)
pd.DataFrame(A)

ind = pd.Index([2, 3, 5, 7, 11])
ind
ind[1]
ind[::2]
print(ind.size, ind.shape, ind.ndim, ind.dtype)
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 6, 11])
indA & indB
indA | indB
indA ^ indB

[(0, 0.) (0, 0.) (0, 0.)]
5 (5,) 1 int64


Index([3, 0, 0, 1, 2], dtype='int64')

In [156]:
import pandas as pd
import numpy as np
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index = ['a', 'b', 'c', 'd'])
data

data['b']
'a' in data # bool statement

data.items() # <zip at 0x117165200>
data.keys() # Index(['a', 'b', 'c', 'd'], dtype='object')
list(data.items()) # [('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
# data['e'] # Notice, this returns an error as 'e' is not included

data['e'] = 1.25 # Adds 'e'
data

data['a':'c']
data[0:2]
data[(data > 0.3) & (data < 0.8)]
data[['a','e']]

data = pd.Series(['a', 'b', 'c'],
                 index = [1, 3, 5])
data
data[1]
data[1:3]
data.loc[1]
data.loc[3]
data.loc[5]
data.loc[1:3]
data.iloc[1:3]

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area,'pop':pop})
data
data['area']
data.area
data.area is data['area']   # True
data.pop is data['pop'] # False
# data['pop'] = z # Is better than data.pop = z

data['density'] = data['pop'] / data['area']
data.columns
data['density']
data
data.values

data = np.transpose(data); data
data = data.T;data

data.values[0]
data['area']
data.iloc[:3, :2]
data.loc[:'Illinois', :'pop']
data.loc[data.density > 100, ['pop', 'density']]
data.loc[data.density < 100, ['pop', 'density']]
data.iloc[0, 2] = 90
data

data['Florida':'Illinois']
data[1:3]
data[data.density > 100]



area         pop     density
New York  141297.0  19651127.0  139.076746
Florida   170312.0  19552860.0  114.806121

In [157]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10, 4))

df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns = ['A', 'B', 'C', 'D'])

df

np.exp(ser)
np.sin(df * np.pi / 4)
np.exp(df)

area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name = 'area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name = 'population')
population / area

A = pd.Series([2, 4, 6], index = [0, 1, 2])
B = pd.Series([1, 3, 5], index = [1, 2, 3])
print("\nA =")
print(A)

print("\nB =")
print(B)

print("\nA + B =")
print(A+B)

print("\nA.add(B, fill_value = 0) = ")
print(A.add(B, fill_value = 0))

A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns = list('AB'))
print('\nA =')
print(A)

B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
print('\nB =')
print(B)

print('\nA + B (no fill_value) =')
print(A + B)

print('\nA + B (fill_value = 0) =')
print(A.add(B, fill_value = 0))

fill = A.stack().mean()
print(fill)
A.add(B, fill_value = fill)

A = rng.randint(10, size =(3, 4))
print('\nA - A[0] =')
print(A - A[0])

df = pd.DataFrame(A, columns = list('QRST'))
print(df)
df - df.iloc[0]
df.subtract(df['R'], axis = 0)

halfrow = df.iloc[0, ::2]
halfrow

df - halfrow


A =
0    2
1    4
2    6
dtype: int64

B =
1    1
2    3
3    5
dtype: int64

A + B =
0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

A.add(B, fill_value = 0) = 
0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

A =
   A   B
0  1  11
1  5   1

B =
   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

A + B (no fill_value) =
      A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

A + B (fill_value = 0) =
      A     B    C
0   1.0  15.0  9.0
1  13.0   6.0  0.0
2   2.0   9.0  6.0
4.5

A - A[0] =
[[ 0  0  0  0]
 [-1 -2  2  4]
 [ 3 -7  1  4]]
   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8


Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

In [158]:
import numpy as np
import pandas as pd

vals1 = np.array([1, None, 3, 4])
vals1
for dtype in ['object', 'int']:
    print('dtype =', dtype)
%timeit np.arange(1E6, dtype=dtype).sum
# vals1.sum() :: Notice: TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

1 + np.nan  # nan
0 * np.nan  # nan

vals2.sum(), vals2.min(), vals2.max()   # (np.float64(nan), np.float64(nan), np.float64(nan))

np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2) # (np.float64(8.0), np.float64(1.0), np.float64(4.0))

pd.Series([1, np.nan, 2, None])

x = pd.Series(range(2), dtype = int)
x
x[0] = None
x

data = pd.Series([1, np.nan, 'hello', None])
data.isnull()
data.notnull()
data[data.notnull()]

data.dropna()

df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df
df.dropna()
df.dropna(axis = 'columns')
df[3] = np.nan
df
df.dropna(axis = 'columns', how = 'all')
df.dropna(axis = 'rows', thresh = 3)

data = pd.Series([1, np.nan, 2, None, 3], index = list('abcde'))
data

# fill.na methods
data.fillna(0)
data.fillna(method = 'ffill')
data.fillna(method = 'bfill')

df
df.fillna(method = 'ffill', axis = 1)


dtype = object
dtype = int
707 μs ± 79.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


/var/folders/nn/rjk_sthj67g1rcv7qxd8_14m0000gn/T/ipykernel_70262/1605124372.py:51: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method = 'ffill')
/var/folders/nn/rjk_sthj67g1rcv7qxd8_14m0000gn/T/ipykernel_70262/1605124372.py:52: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method = 'bfill')
/var/folders/nn/rjk_sthj67g1rcv7qxd8_14m0000gn/T/ipykernel_70262/1605124372.py:55: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill', axis = 1)


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [159]:
import pandas as pd
import numpy as np

index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]

populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

pop = pd.Series(populations, index = index)
print('pop =\n', pop)

pop[('California', 2010):('Texas', 2000)]
pop[[i for i in pop.index if i[1] == 2010]]

index = pd.MultiIndex.from_tuples(index)
index

pop = pop.reindex(index)
print('\npop  =\n', pop)

pop[:, 2000]
pop[:, 2010]

pop_df = pop.unstack()
print('\npop_df =   \n', pop_df)

print('\npop_df.stack() =   \n', pop_df.stack())

pop_df = pd.DataFrame({'total': pop,
                       'under18':[9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})

print('\npop_df (including under18\'s and total)  \n    =\n', pop_df)

f_u18 = pop_df['under18'] / pop_df['total']
print('\nf_u18.unstack()  =\n', f_u18.unstack())

df = pd.DataFrame(np.random.rand(4, 2),
                  index = [['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns = ['data1', 'data2'])
print('\ndf =   \n', df) 

pop =
 (California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

pop  =
 California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

pop_df =   
                 2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

pop_df.stack() =   
 California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

pop_df (including under18's and total)  
    =
                     total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  

In [ ]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
data = pd.Series(data)
data = data.unstack()
data

pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

pop.index.names = ['state', 'year']
pop
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [204]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

health_data = pd.DataFrame(data, index=index, columns=columns)
print('\nhealth_data  =   \n', health_data)

print('\nhealth_data[\'Guido\']  =\n', health_data['Guido'])
print('\nhealth_data[\'Guido\', \'HR\']  =\n', health_data['Guido', 'HR'])
print('\nhealth_data.iloc[:2,:2] =\n',health_data.iloc[:2, :2])
print('\nhealth_data.loc[:, (\'Bob\', \'HR\')]    \n    =\n', health_data.loc[:, ('Bob', 'HR')])

idx = pd.IndexSlice
print('\nhealth_data.loc[idx[:, 1], idx[:, \'HR\']]\n   =\n', health_data.loc[idx[:, 1], idx[:, 'HR']])

index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index = index)
data.index.names = ['char', 'int']
data

data = data.sort_index()
data
print('\npop.unstack(level = 0) =\n', pop.unstack(level = 0))
print('\npop.unstack(level = 1) =\n', pop.unstack(level = 1))
print('\npop.unstack().stack  =\n', pop.unstack().stack())

pop_flat = pop.reset_index(name = 'population')
pop_flat
pop_flat.set_index(['state', 'year'])

health_data
data_mean = health_data.mean()
print('\ndata_mean    =\n', data_mean)



health_data  =   
 subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      54.0  38.1  29.0  36.6  38.0  38.1
     2      30.0  38.2  41.0  35.4  27.0  37.9
2014 1      51.0  37.7  45.0  36.8  39.0  37.0
     2      40.0  37.9  21.0  37.3  47.0  37.0

health_data['Guido']  =
 type          HR  Temp
year visit            
2013 1      29.0  36.6
     2      41.0  35.4
2014 1      45.0  36.8
     2      21.0  37.3

health_data['Guido', 'HR']  =
 year  visit
2013  1        29.0
      2        41.0
2014  1        45.0
      2        21.0
Name: (Guido, HR), dtype: float64

health_data.iloc[:2,:2] =
 subject      Bob      
type          HR  Temp
year visit            
2013 1      54.0  38.1
     2      30.0  38.2

health_data.loc[:, ('Bob', 'HR')]    
    =
 year  visit
2013  1        54.0
      2        30.0
2014  1        51.0
      2        40.0
Name: (Bob, HR), dtype: float64

health_data.loc

In [ ]:
import pandas as pd
import numpy as np

def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

make_df('ABC', range(3))

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style = "float: left, padding: 10px;">
    <p style = 'font-family:"Courier New,", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
    
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)
                           

In [82]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

x = [[1, 2],
     [3, 4]]
np. concatenate([x, x], axis = 0)
np.concatenate([x, x], axis = 1)

ser1 = pd.Series(['A', 'B', 'C'], index = [1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index = [4, 5, 6])
pd.concat([ser1, ser2])

df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
display('df1', 'df2', 'pd.concat([df1, df2])')

df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
display('df3', 'df4', "pd.concat([df3, df4], axis = 1)")

x = make_df(cols = 'AB', ind = [0, 1])
y = make_df(cols = 'AB', ind = [2, 3])
y.index = x.index
display('x', 'y', 'pd.concat([x, y])')

try:
    pd.concat([x, y], verify_integrity = True)
except ValueError as e:
    print("ValueError:", e)

display('x', 'y', 'pd.concat([x, y], ignore_index = True)')

display('x', 'y', "pd.concat([x, y], keys = ['x', 'y'])")

df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
display('df5', 'df6', 'pd.concat([df5, df6])')

display('df5', 'df6',
        "pd.concat([df5, df6], join = 'inner')")

ValueError: Indexes have overlapping values: Index([0, 1], dtype='int64')


df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join = 'inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')
df3 = pd.merge(df1, df2)
df3
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
display('df3', 'df4', 'pd.merge(df3, df4)')
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
display('df1', 'df5', "pd.merge(df1, df5)")
display('df1', 'df2', "pd.merge(df1, df2, on='employee')")
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
display('df1', 'df3', 'pd.merge(df1, df3, left_on="employee", right_on="name")')
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

display('df1a', 'df2a')
display('df1a', 'df2a', "pd.merge(df1a, df2a, left_index = True, right_index = True)")
display('df1a', 'df2a', 'df1a.join(df2a)')
display('df1a', 'df3', "pd.merge(df1a, df3, left_index=True, right_on='name')")

df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df3
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

pd.merge(df1a, df3, left_index=True, right_on='name')
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

In [ ]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])

display('df6', 'df7', 'pd.merge(df6, df7)')

pd.merge(df6, df7, how='inner')

display('df6', 'df7', "pd.merge(df6, df7, how='outer')")
display('df6', 'df7', "pd.merge(df6, df7, how='left')")

df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})

display('df8', 'df9', 'pd.merge(df8, df9, on="name")')
display('df8', 'df9', 'pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])')



df8
   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

df9
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])
   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [100]:
# Following are shell commands to download the data
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57935  100 57935    0     0   183k      0 --:--:-- --:--:-- --:--:--  184k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   835  100   835    0     0   3726      0 --:--:-- --:--:-- --:--:--  3744
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   872  100   872    0     0   3954      0 --:--:-- --:--:-- --:--:--  3963


In [139]:
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')
display('pop.head()', 'areas.head()', 'abbrevs.head()')

merged = pd.merge(pop, abbrevs, how = 'outer',
                  left_on = 'state/region', 
                  right_on = 'abbreviation')
merged = merged.drop(columns='abbreviation')
merged.head()
merged.isnull().any()
merged[merged['population'].isnull()].head()

merged.loc[merged['state'].isnull(), 'state/region'].unique()

merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

final = pd.merge(merged, areas, on='state', how='left')
final.head()
final.isnull().any()
final['state'][final['area (sq. mi)'].isnull()].unique()
final.dropna(inplace=True)
final.head()

data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()
data2010.set_index('state', inplace=True)
density = data2010['population'] / data2010['area (sq. mi)']
density.sort_values(ascending=False, inplace=True)
density.head()
density.tail()


state
South Dakota    10.583512
North Dakota     9.537565
Montana          6.736171
Wyoming          5.768079
Alaska           1.087509
dtype: float64